"""
Test Generation Plugin for A.N.A.
=================================
Provides a tool to generate basic pytest unit tests for Python files.
"""

import os
from plugins import Plugin, PluginMetadata
from typing import List, Callable, Optional


class TestGenPlugin(Plugin):
    """Plugin: Test Generation"""
    
    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name="test_gen_plugin",
            version="1.0.0",
            description="Generates pytest unit tests for Python modules",
            author="Antigravity",
            capabilities=["test_generation"]
        )
    
    def initialize(self) -> bool:
        return True
    
    def get_tools(self) -> List[Callable]:
        return [self.generate_tests]
    
    def generate_tests(self, file_path: str) -> str:
        """
        Generates a pytest file for the specified Python file.
        
        Args:
            file_path: Path to the .py file to test
        """
        if not os.path.exists(file_path):
            return f"Error: File {file_path} not found."
            
        if not file_path.endswith(".py"):
            return "Error: Only Python files are supported."
            
        base_name = os.path.basename(file_path)
        dir_name = os.path.dirname(file_path)
        test_file_name = f"test_{base_name}"
        test_file_path = os.path.join(dir_name, test_file_name)
        
        if os.path.exists(test_file_path):
            return f"Error: Test file {test_file_path} already exists."
            
        module_name = base_name[:-3]
        
        template = f"""import pytest
from {module_name} import *

def test_basic():
    # TODO: Add specific tests for {module_name}
    assert True

# Auto-generated by A.N.A. TestGenPlugin
"""
        try:
            with open(test_file_path, "w") as f:
                f.write(template)
            return f"Successfully generated {test_file_path}"
        except Exception as e:
            return f"Error writing test file: {str(e)}"
    
    def cleanup(self) -> None:
        pass
